Update main.yml
added debug for token

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -38,3 +38,11 @@ jobs:
       - name: Deploy to Vercel (Production)
         if: github.ref == 'refs/heads/main'
         run: npx vercel --prod --cwd=. --token=${{ secrets.WfSYUi30dHt5vJ5GB0XKUVg7 }} --scope=${{ secrets.team_8kXRHgQOIxU0PUWLPWDoW4Rw }} --project=${{ secrets.prj_Rhdn03DuBNyGFiP2UOxtQRipDBGd }} --confirm
+      - name: Debug secrets
+          run:|
+          if [ -z "${{ secrets.VERCEL_TOKEN }}" ]; then
+          echo "❌ VERCEL_TOKEN is missing"
+            exit 1
+              else
+            echo "✅ VERCEL_TOKEN is set"
+            fi
